version: '3'
services:
  node:
    container_name: node
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
    networks:
      - voting
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=mydb
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db
    networks:
      - voting
networks:
  voting:
